services:
  whisper:
    build: ./src
    command: python main.py
    volumes:
      - ./src:/app

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [ gpu ]
